In [1]:
import pandas as pd
import json
import open3d as o3d
import pickle 
import os
import numpy as np

ModuleNotFoundError: No module named 'pandas'

In [6]:
json_path = "G:\내 드라이브\data\AIhub\특수환경 자율주행 3D 이미지\Training\[라벨]seoul1\drive_620\meta\drive_620_000000.json"

In [7]:
with open(json_path, 'r') as f:
    label_json = json.load(f)
print(json.dumps(label_json))

{"IMAGE_INFO": {"CAMETA_NAME": "front", "DATA_COLLECTION_TIME": "20201023_131656", "WEATHER": 1, "TEMPERTATURE": 11.4, "HUMIDITY": 39, "DATA_COLLECTION_AREA": [{"LATITUDE": "37.409306", "HARDNESS": "127.094715"}], "ROAD_TYPE": "R", "ROAD_TYPE_CLASSIFICATION": "E", "ACQUISITION_TIME": "D", "COLLECTION_ORGANIZATION": "mobiltech", "DATA_SIZE": 1.1, "TEMPERATURE": "Y,U", "Vehicle Model": "KIA Morning", "IMAGE_PATH": "\\drive_620\\image_0\\drive_620_000000.jpg", "IMAGE_HEIGHT": 1200, "IMAGE_WIDTH": 1920}, "OBJECT_LIST": [{"2D_LIST": [{"POLYGON": [472, 743, 845, 734, 1328, 711, 1433, 706, 1555, 698, 1559, 710, 1307, 719, 780, 744, 471, 751], "COLOR": "WHITE", "COUNT": "1", "CLASS": "LANE", "TYPE": "DASHED"}, {"POLYGON": [3, 900, 621, 876, 1001, 858, 1295, 834, 1576, 807, 1776, 784, 1780, 807, 1309, 840, 959, 870, 611, 886, 0, 915], "COLOR": "YELLOW", "COUNT": "1", "CLASS": "LANE", "TYPE": "SOLID"}, {"POLYGON": [0, 647, 207, 644, 559, 636, 817, 628, 1051, 619, 1727, 605, 1795, 605, 1877, 604,

In [18]:
class Fusion3D:
    def __init__(self, json_label):
        r'''
        json_label
        '''
        self.img_info = json_label["IMAGE_INFO"]
        self.img_path = self.img_info["IMAGE_PATH"]
        self.height = self.img_info["IMAGE_HEIGHT"]
        self.width = self.img_info["IMAGE_WIDTH"]

        self.ObjList2D = json_label["OBJECT_LIST"][0]["2D_LIST"]
        self.ObjList3D = json_label["OBJECT_LIST"][0]["3D_LIST"]
        
    def Anno2D(self):
        num_2D = len(self.ObjList2D)
    
        
        

In [ ]:
def label2color(label):
    colors = [204/255, 0, 0], [52/255, 101/255, 164/255],
    [245/255, 121/255, 0]

    return colors[label]

'''with open(lidar_root, 'rb') as f:
    data_dicts 
    '''

In [14]:
lidar_root = 'G:/내 드라이브/data/AIhub/Auto3D/Training/[원천]seoul1/drive_630/lidar'

points = o3d.io.read_point_cloud(os.path.join(lidar_root, "000400.pcd"))



In [23]:
print(np.asarray(points.points))

[[12.00068188  1.89336836 -1.99602783]
 [ 0.71993887  0.11353127 -0.4095054 ]
 [14.11725998  2.22515821 -2.00854611]
 ...
 [ 0.          0.          0.        ]
 [10.40058041  1.54695475 -1.98112738]
 [ 0.          0.          0.        ]]


In [19]:
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(np.asarray(points.points))
visual = [pcd]
num_dets = detections['']
o3d.visualization.draw_geometries(visual)